server:
  port: 8081

spring:
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: baidu_route
          uri: https://www.baidu.com
          predicates:
            - Path=/**
