server:
  port: 8080

spring:
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8081
          predicates:
            - Path=/identify/**
          filters:
            - StripPrefix=1
