server:
  port: 8082

spring:
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    doc-expansion: list
    enabled: false
  api-docs:
    path: /v3/api-docs
    enabled: false